/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiPatMed;

/**
 *
 * @author maximeriskwait
 */
public class fenetrePatMed extends javax.swing.JFrame {

    /**
     * Creates new form fenetrePatMed
     */
    public fenetrePatMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ongletPatMed = new javax.swing.JTabbedPane();
        ongletPatient = new javax.swing.JPanel();
        spPat = new javax.swing.JScrollPane();
        listePatient = new javax.swing.JList<>();
        addNewPatient = new javax.swing.JButton();
        recherchePat = new javax.swing.JTextField();
        ongletMedecin = new javax.swing.JPanel();
        spMed = new javax.swing.JScrollPane();
        listeMedecin = new javax.swing.JList<>();
        rechercheMed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Médical");

        listePatient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Patient 1 ", "Patient 2", "Patient 3", "Patient 4", "Patient 5", "Patient 6", "Patient 7", "Patient 8", "Patient 9", "Patient 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spPat.setViewportView(listePatient);

        addNewPatient.setText("Nouveau Patient");
        addNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPatientActionPerformed(evt);
            }
        });

        recherchePat.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        recherchePat.setText("Rechercher un patient");

        javax.swing.GroupLayout ongletPatientLayout = new javax.swing.GroupLayout(ongletPatient);
        ongletPatient.setLayout(ongletPatientLayout);
        ongletPatientLayout.setHorizontalGroup(
            ongletPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletPatientLayout.createSequentialGroup()
                .addGroup(ongletPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ongletPatientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spPat))
                    .addGroup(ongletPatientLayout.createSequentialGroup()
                        .addComponent(addNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(recherchePat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ongletPatientLayout.setVerticalGroup(
            ongletPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spPat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ongletPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewPatient)
                    .addComponent(recherchePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ongletPatMed.addTab("Patient", ongletPatient);

        listeMedecin.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Médecin 1", "Médecin 2", "Médecin 3", "Médecin 1", "Médecin 2", "Médecin 3", "Médecin 1", "Médecin 2", "Médecin 3", "Médecin 1", "Médecin 2", "Médecin 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spMed.setViewportView(listeMedecin);

        rechercheMed.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        rechercheMed.setText("Rechercher un medecin");
        rechercheMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ongletMedecinLayout = new javax.swing.GroupLayout(ongletMedecin);
        ongletMedecin.setLayout(ongletMedecinLayout);
        ongletMedecinLayout.setHorizontalGroup(
            ongletMedecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletMedecinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ongletMedecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMed)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ongletMedecinLayout.createSequentialGroup()
                        .addGap(0, 389, Short.MAX_VALUE)
                        .addComponent(rechercheMed, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ongletMedecinLayout.setVerticalGroup(
            ongletMedecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletMedecinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMed, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rechercheMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        ongletPatMed.addTab("Médecin", ongletMedecin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ongletPatMed)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ongletPatMed)
        );

        ongletPatMed.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewPatientActionPerformed

    private void rechercheMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetrePatMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetrePatMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetrePatMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetrePatMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetrePatMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewPatient;
    private javax.swing.JList<String> listeMedecin;
    private javax.swing.JList<String> listePatient;
    private javax.swing.JPanel ongletMedecin;
    private javax.swing.JTabbedPane ongletPatMed;
    private javax.swing.JPanel ongletPatient;
    private javax.swing.JTextField rechercheMed;
    private javax.swing.JTextField recherchePat;
    private javax.swing.JScrollPane spMed;
    private javax.swing.JScrollPane spPat;
    // End of variables declaration//GEN-END:variables
}
